/*
 Ardiono pin mapping is very logical: ArduinoPin = port * 16 + portpin
 With port = 0 for port A until 4 for port E, portpin is 0..15
Symbolic names PA0 - PE15 are defined already in variant.h!

*/

#ifndef _FASTIO_H
#define _FASTIO_H

#include "PinNames.h"
#include "PortNames.h"
#include "stm32yyxx_ll_gpio.h"

// Port A
#define GPIO_0 GPIOA
#define GPIO_1 GPIOA
#define GPIO_2 GPIOA
#define GPIO_3 GPIOA
#define GPIO_4 GPIOA
#define GPIO_5 GPIOA
#define GPIO_6 GPIOA
#define GPIO_7 GPIOA
#define GPIO_8 GPIOA
#define GPIO_9 GPIOA
#define GPIO_10 GPIOA
#define GPIO_11 GPIOA
#define GPIO_12 GPIOA
#define GPIO_13 GPIOA
#define GPIO_14 GPIOA
#define GPIO_15 GPIOA

#define GPIO_0_MASK LL_GPIO_PIN_0
#define GPIO_1_MASK LL_GPIO_PIN_1
#define GPIO_2_MASK LL_GPIO_PIN_2
#define GPIO_3_MASK LL_GPIO_PIN_3
#define GPIO_4_MASK LL_GPIO_PIN_4
#define GPIO_5_MASK LL_GPIO_PIN_5
#define GPIO_6_MASK LL_GPIO_PIN_6
#define GPIO_7_MASK LL_GPIO_PIN_7
#define GPIO_8_MASK LL_GPIO_PIN_8
#define GPIO_9_MASK LL_GPIO_PIN_9
#define GPIO_10_MASK LL_GPIO_PIN_10
#define GPIO_11_MASK LL_GPIO_PIN_11
#define GPIO_12_MASK LL_GPIO_PIN_12
#define GPIO_13_MASK LL_GPIO_PIN_13
#define GPIO_14_MASK LL_GPIO_PIN_14
#define GPIO_15_MASK LL_GPIO_PIN_15

// Port B
#define GPIO_16 GPIOB
#define GPIO_17 GPIOB
#define GPIO_18 GPIOB
#define GPIO_19 GPIOB
#define GPIO_20 GPIOB
#define GPIO_21 GPIOB
#define GPIO_22 GPIOB
#define GPIO_23 GPIOB
#define GPIO_24 GPIOB
#define GPIO_25 GPIOB
#define GPIO_26 GPIOB
#define GPIO_27 GPIOB
#define GPIO_28 GPIOB
#define GPIO_29 GPIOB
#define GPIO_30 GPIOB
#define GPIO_31 GPIOB

#define GPIO_16_MASK LL_GPIO_PIN_0
#define GPIO_17_MASK LL_GPIO_PIN_1
#define GPIO_18_MASK LL_GPIO_PIN_2
#define GPIO_19_MASK LL_GPIO_PIN_3
#define GPIO_20_MASK LL_GPIO_PIN_4
#define GPIO_21_MASK LL_GPIO_PIN_5
#define GPIO_22_MASK LL_GPIO_PIN_6
#define GPIO_23_MASK LL_GPIO_PIN_7
#define GPIO_24_MASK LL_GPIO_PIN_8
#define GPIO_25_MASK LL_GPIO_PIN_9
#define GPIO_26_MASK LL_GPIO_PIN_10
#define GPIO_27_MASK LL_GPIO_PIN_11
#define GPIO_28_MASK LL_GPIO_PIN_12
#define GPIO_29_MASK LL_GPIO_PIN_13
#define GPIO_30_MASK LL_GPIO_PIN_14
#define GPIO_31_MASK LL_GPIO_PIN_15

// Port C
#if defined(GPIOC_BASE)
#define GPIO_32 GPIOC
#define GPIO_33 GPIOC
#define GPIO_34 GPIOC
#define GPIO_35 GPIOC
#define GPIO_36 GPIOC
#define GPIO_37 GPIOC
#define GPIO_38 GPIOC
#define GPIO_39 GPIOC
#define GPIO_40 GPIOC
#define GPIO_41 GPIOC
#define GPIO_42 GPIOC
#define GPIO_43 GPIOC
#define GPIO_44 GPIOC
#define GPIO_45 GPIOC
#define GPIO_46 GPIOC
#define GPIO_47 GPIOC

#define GPIO_32_MASK LL_GPIO_PIN_0
#define GPIO_33_MASK LL_GPIO_PIN_1
#define GPIO_34_MASK LL_GPIO_PIN_2
#define GPIO_35_MASK LL_GPIO_PIN_3
#define GPIO_36_MASK LL_GPIO_PIN_4
#define GPIO_37_MASK LL_GPIO_PIN_5
#define GPIO_38_MASK LL_GPIO_PIN_6
#define GPIO_39_MASK LL_GPIO_PIN_7
#define GPIO_40_MASK LL_GPIO_PIN_8
#define GPIO_41_MASK LL_GPIO_PIN_9
#define GPIO_42_MASK LL_GPIO_PIN_10
#define GPIO_43_MASK LL_GPIO_PIN_11
#define GPIO_44_MASK LL_GPIO_PIN_12
#define GPIO_45_MASK LL_GPIO_PIN_13
#define GPIO_46_MASK LL_GPIO_PIN_14
#define GPIO_47_MASK LL_GPIO_PIN_15
#endif

// Port D
#if defined(GPIOD_BASE)
#define GPIO_48 GPIOD
#define GPIO_49 GPIOD
#define GPIO_50 GPIOD
#define GPIO_51 GPIOD
#define GPIO_52 GPIOD
#define GPIO_53 GPIOD
#define GPIO_54 GPIOD
#define GPIO_55 GPIOD
#define GPIO_56 GPIOD
#define GPIO_57 GPIOD
#define GPIO_58 GPIOD
#define GPIO_59 GPIOD
#define GPIO_60 GPIOD
#define GPIO_61 GPIOD
#define GPIO_62 GPIOD
#define GPIO_63 GPIOD

#define GPIO_48_MASK LL_GPIO_PIN_0
#define GPIO_49_MASK LL_GPIO_PIN_1
#define GPIO_50_MASK LL_GPIO_PIN_2
#define GPIO_51_MASK LL_GPIO_PIN_3
#define GPIO_52_MASK LL_GPIO_PIN_4
#define GPIO_53_MASK LL_GPIO_PIN_5
#define GPIO_54_MASK LL_GPIO_PIN_6
#define GPIO_55_MASK LL_GPIO_PIN_7
#define GPIO_56_MASK LL_GPIO_PIN_8
#define GPIO_57_MASK LL_GPIO_PIN_9
#define GPIO_58_MASK LL_GPIO_PIN_10
#define GPIO_59_MASK LL_GPIO_PIN_11
#define GPIO_60_MASK LL_GPIO_PIN_12
#define GPIO_61_MASK LL_GPIO_PIN_13
#define GPIO_62_MASK LL_GPIO_PIN_14
#define GPIO_63_MASK LL_GPIO_PIN_15
#endif

// Port E
#if defined(GPIOE_BASE)
#define GPIO_64 GPIOE
#define GPIO_65 GPIOE
#define GPIO_66 GPIOE
#define GPIO_67 GPIOE
#define GPIO_68 GPIOE
#define GPIO_69 GPIOE
#define GPIO_70 GPIOE
#define GPIO_71 GPIOE
#define GPIO_72 GPIOE
#define GPIO_73 GPIOE
#define GPIO_74 GPIOE
#define GPIO_75 GPIOE
#define GPIO_76 GPIOE
#define GPIO_77 GPIOE
#define GPIO_78 GPIOE
#define GPIO_79 GPIOE

#define GPIO_64_MASK LL_GPIO_PIN_0
#define GPIO_65_MASK LL_GPIO_PIN_1
#define GPIO_66_MASK LL_GPIO_PIN_2
#define GPIO_67_MASK LL_GPIO_PIN_3
#define GPIO_68_MASK LL_GPIO_PIN_4
#define GPIO_69_MASK LL_GPIO_PIN_5
#define GPIO_70_MASK LL_GPIO_PIN_6
#define GPIO_71_MASK LL_GPIO_PIN_7
#define GPIO_72_MASK LL_GPIO_PIN_8
#define GPIO_73_MASK LL_GPIO_PIN_9
#define GPIO_74_MASK LL_GPIO_PIN_10
#define GPIO_75_MASK LL_GPIO_PIN_11
#define GPIO_76_MASK LL_GPIO_PIN_12
#define GPIO_77_MASK LL_GPIO_PIN_13
#define GPIO_78_MASK LL_GPIO_PIN_14
#define GPIO_79_MASK LL_GPIO_PIN_15
#endif

// Port F
#if defined(GPIOF_BASE)
#define GPIO_80 GPIOF
#define GPIO_81 GPIOF
#define GPIO_82 GPIOF
#define GPIO_83 GPIOF
#define GPIO_84 GPIOF
#define GPIO_85 GPIOF
#define GPIO_86 GPIOF
#define GPIO_87 GPIOF
#define GPIO_88 GPIOF
#define GPIO_89 GPIOF
#define GPIO_90 GPIOF
#define GPIO_91 GPIOF
#define GPIO_92 GPIOF
#define GPIO_93 GPIOF
#define GPIO_94 GPIOF
#define GPIO_95 GPIOF

#define GPIO_80_MASK LL_GPIO_PIN_0
#define GPIO_81_MASK LL_GPIO_PIN_1
#define GPIO_82_MASK LL_GPIO_PIN_2
#define GPIO_83_MASK LL_GPIO_PIN_3
#define GPIO_84_MASK LL_GPIO_PIN_4
#define GPIO_85_MASK LL_GPIO_PIN_5
#define GPIO_86_MASK LL_GPIO_PIN_6
#define GPIO_87_MASK LL_GPIO_PIN_7
#define GPIO_88_MASK LL_GPIO_PIN_8
#define GPIO_89_MASK LL_GPIO_PIN_9
#define GPIO_90_MASK LL_GPIO_PIN_10
#define GPIO_91_MASK LL_GPIO_PIN_11
#define GPIO_92_MASK LL_GPIO_PIN_12
#define GPIO_93_MASK LL_GPIO_PIN_13
#define GPIO_94_MASK LL_GPIO_PIN_14
#define GPIO_95_MASK LL_GPIO_PIN_15
#endif

// Port G
#if defined(GPIOG_BASE)
#define GPIO_96 GPIOG
#define GPIO_97 GPIOG
#define GPIO_98 GPIOG
#define GPIO_99 GPIOG
#define GPIO_100 GPIOG
#define GPIO_101 GPIOG
#define GPIO_102 GPIOG
#define GPIO_103 GPIOG
#define GPIO_104 GPIOG
#define GPIO_105 GPIOG
#define GPIO_106 GPIOG
#define GPIO_107 GPIOG
#define GPIO_108 GPIOG
#define GPIO_109 GPIOG
#define GPIO_110 GPIOG
#define GPIO_111 GPIOG

#define GPIO_96_MASK LL_GPIO_PIN_0
#define GPIO_97_MASK LL_GPIO_PIN_1
#define GPIO_98_MASK LL_GPIO_PIN_2
#define GPIO_99_MASK LL_GPIO_PIN_3
#define GPIO_100_MASK LL_GPIO_PIN_4
#define GPIO_101_MASK LL_GPIO_PIN_5
#define GPIO_102_MASK LL_GPIO_PIN_6
#define GPIO_103_MASK LL_GPIO_PIN_7
#define GPIO_104_MASK LL_GPIO_PIN_8
#define GPIO_105_MASK LL_GPIO_PIN_9
#define GPIO_106_MASK LL_GPIO_PIN_10
#define GPIO_107_MASK LL_GPIO_PIN_11
#define GPIO_108_MASK LL_GPIO_PIN_12
#define GPIO_109_MASK LL_GPIO_PIN_13
#define GPIO_110_MASK LL_GPIO_PIN_14
#define GPIO_111_MASK LL_GPIO_PIN_15
#endif

// Port H
#if defined(GPIOH_BASE)
#define GPIO_112 GPIOH
#define GPIO_113 GPIOH
#define GPIO_114 GPIOH
#define GPIO_115 GPIOH
#define GPIO_116 GPIOH
#define GPIO_117 GPIOH
#define GPIO_118 GPIOH
#define GPIO_119 GPIOH
#define GPIO_120 GPIOH
#define GPIO_121 GPIOH
#define GPIO_122 GPIOH
#define GPIO_123 GPIOH
#define GPIO_124 GPIOH
#define GPIO_125 GPIOH
#define GPIO_126 GPIOH
#define GPIO_127 GPIOH

#define GPIO_112_MASK LL_GPIO_PIN_0
#define GPIO_113_MASK LL_GPIO_PIN_1
#define GPIO_114_MASK LL_GPIO_PIN_2
#define GPIO_115_MASK LL_GPIO_PIN_3
#define GPIO_116_MASK LL_GPIO_PIN_4
#define GPIO_117_MASK LL_GPIO_PIN_5
#define GPIO_118_MASK LL_GPIO_PIN_6
#define GPIO_119_MASK LL_GPIO_PIN_7
#define GPIO_120_MASK LL_GPIO_PIN_8
#define GPIO_121_MASK LL_GPIO_PIN_9
#define GPIO_122_MASK LL_GPIO_PIN_10
#define GPIO_123_MASK LL_GPIO_PIN_11
#define GPIO_124_MASK LL_GPIO_PIN_12
#define GPIO_125_MASK LL_GPIO_PIN_13
#define GPIO_126_MASK LL_GPIO_PIN_14
#define GPIO_127_MASK LL_GPIO_PIN_15
#endif

// Port I
#if defined(GPIOI_BASE)
#define GPIO_128 GPIOI
#define GPIO_129 GPIOI
#define GPIO_130 GPIOI
#define GPIO_131 GPIOI
#define GPIO_132 GPIOI
#define GPIO_133 GPIOI
#define GPIO_134 GPIOI
#define GPIO_135 GPIOI
#define GPIO_136 GPIOI
#define GPIO_137 GPIOI
#define GPIO_138 GPIOI
#define GPIO_139 GPIOI
#define GPIO_140 GPIOI
#define GPIO_141 GPIOI
#define GPIO_142 GPIOI
#define GPIO_143 GPIOI

#define GPIO_128_MASK LL_GPIO_PIN_0
#define GPIO_129_MASK LL_GPIO_PIN_1
#define GPIO_130_MASK LL_GPIO_PIN_2
#define GPIO_131_MASK LL_GPIO_PIN_3
#define GPIO_132_MASK LL_GPIO_PIN_4
#define GPIO_133_MASK LL_GPIO_PIN_5
#define GPIO_134_MASK LL_GPIO_PIN_6
#define GPIO_135_MASK LL_GPIO_PIN_7
#define GPIO_136_MASK LL_GPIO_PIN_8
#define GPIO_137_MASK LL_GPIO_PIN_9
#define GPIO_138_MASK LL_GPIO_PIN_10
#define GPIO_139_MASK LL_GPIO_PIN_11
#define GPIO_140_MASK LL_GPIO_PIN_12
#define GPIO_141_MASK LL_GPIO_PIN_13
#define GPIO_142_MASK LL_GPIO_PIN_14
#define GPIO_143_MASK LL_GPIO_PIN_15
#endif

#endif /* _FASTIO_H */
